version: "3.8"
services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/taskhub
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
